apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-summarizer-deployment
  labels:
    app: clinical-summarizer
spec:
  replicas: 1
  progressDeadlineSeconds: 1200
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: clinical-summarizer
  template:
    metadata:
      labels:
        app: clinical-summarizer
    spec:
      containers:
        - name: clinical-summarizer-app
          image: northamerica-northeast2-docker.pkg.dev/clinicalsummarizer/clinical-summarizer-repo/clinical-summarizer-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # Speed up startup in cluster by using a tiny model for smoke checks
            - name: MODEL_DIR
              value: hf-internal-testing/tiny-random-t5
            - name: USE_FAST_TOKENIZER
              value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            # Allow longer time for image pull and initial model load
            failureThreshold: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3



