"""FastAPI service for clinical note summarization.

Loads a FLAN-T5 model (local directory, environment override, or public
Hugging Face checkpoint) and exposes ``/summarize`` for generating
patient-friendly summaries of clinical notes. Includes basic per-IP rate
limiting, CORS, and health/readiness endpoints suitable for Kubernetes.
"""

from __future__ import annotations

import logging
import os
import time
from contextlib import asynccontextmanager
from pathlib import Path

import torch
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, ConfigDict, Field
from starlette.requests import Request as StarletteRequest
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_MODEL_DIR = Path("models/flan-t5-bhc-summarizer")
FALLBACK_MODEL_NAME = "google/flan-t5-base"
MAX_INPUT_CHARS = int(os.getenv("MAX_INPUT_CHARS", "10000"))
RATE_LIMIT_MAX = int(os.getenv("RATE_LIMIT_MAX", "30"))
RATE_LIMIT_WINDOW_SEC = int(os.getenv("RATE_LIMIT_WINDOW_SEC", "60"))
FRONTEND_DIST = Path(os.getenv("FRONTEND_DIST", "web/dist"))

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("summarizer")


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------


class InputData(BaseModel):
    """Request body for the ``/summarize`` endpoint."""

    text: str = Field(..., min_length=1, description="Full clinical note to summarize")
    max_new_tokens: int | None = Field(
        256, ge=1, le=1024, description="Maximum new tokens generated by the model"
    )
    temperature: float | None = Field(
        0.0, ge=0.0, le=1.0, description="Sampling temperature. 0 = greedy/beam search"
    )


class PredictionResponse(BaseModel):
    """Response body for ``/summarize``."""

    summary: str


class HealthResponse(BaseModel):
    """Response body for ``/health`` and ``/ready``."""

    model_config = ConfigDict(protected_namespaces=())

    status: str
    model_loaded: bool


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _resolve_model_source() -> str:
    """Return the local path or HF model id to load from.

    Resolution order:
    1. ``MODEL_DIR`` environment variable (local path or HF model id).
    2. Local ``models/flan-t5-bhc-summarizer`` if ``config.json`` is present.
    3. The public ``google/flan-t5-base`` checkpoint as a fallback.
    """
    env_path = os.getenv("MODEL_DIR")
    if env_path:
        return env_path
    if (DEFAULT_MODEL_DIR / "config.json").exists():
        return str(DEFAULT_MODEL_DIR)
    return FALLBACK_MODEL_NAME


def _get_device() -> torch.device:
    """Select the best available torch device (CUDA > MPS > CPU)."""
    if torch.cuda.is_available():
        return torch.device("cuda")
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def _parse_cors_origins() -> list[str]:
    """Parse ``CORS_ORIGINS`` env var into a list.

    Defaults to localhost dev origins. Set ``CORS_ORIGINS="*"`` to allow
    any origin (not recommended in production).
    """
    raw = os.getenv("CORS_ORIGINS", "http://localhost:3000,http://localhost:5173")
    return [o.strip() for o in raw.split(",") if o.strip()]


def _rate_limit_check(app: FastAPI, ip: str) -> None:
    """Apply a naive in-memory, per-IP sliding-window rate limit.

    Shared state is kept on ``app.state.rate_buckets``. This is intended
    for demos and local development; use Redis or an API gateway for
    production multi-replica deployments.
    """
    now = time.time()
    bucket = app.state.rate_buckets.get(ip, [])
    bucket = [t for t in bucket if now - t < RATE_LIMIT_WINDOW_SEC]
    if len(bucket) >= RATE_LIMIT_MAX:
        raise HTTPException(
            status_code=429,
            detail="Rate limit exceeded. Please try again later.",
        )
    bucket.append(now)
    app.state.rate_buckets[ip] = bucket


# ---------------------------------------------------------------------------
# Application lifespan
# ---------------------------------------------------------------------------


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the model/tokenizer at startup; clean up on shutdown.

    If loading fails (e.g. no network, missing files), the service starts
    in *stub mode* and returns a simple truncation of the input so that
    Kubernetes probes still succeed and the UI remains interactive.
    """
    model_src = _resolve_model_source()
    device = _get_device()

    app.state.tokenizer = None
    app.state.model = None
    app.state.device = device
    app.state.stub_mode = False
    app.state.rate_buckets: dict[str, list[float]] = {}

    use_fast_env = os.getenv("USE_FAST_TOKENIZER", "").lower() in {"1", "true", "yes"}
    try:
        try:
            tokenizer = AutoTokenizer.from_pretrained(model_src, use_fast=use_fast_env)
        except Exception:
            tokenizer = AutoTokenizer.from_pretrained(model_src, use_fast=not use_fast_env)
        model = AutoModelForSeq2SeqLM.from_pretrained(model_src)
        model.to(device)
        model.eval()

        app.state.tokenizer = tokenizer
        app.state.model = model
        logger.info("model_loaded source=%s device=%s", model_src, device)
    except Exception as exc:  # pragma: no cover - exercised only on failure
        app.state.stub_mode = True
        logger.warning("model_load_failed source=%s error=%s; running in stub mode", model_src, exc)

    try:
        yield
    finally:
        app.state.model = None
        app.state.tokenizer = None


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Clinical Note Summarizer",
    description=(
        "FLAN-T5-based summarization service for clinical notes. "
        "Informational demo only; not a medical device."
    ),
    version="0.1.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=_parse_cors_origins(),
    allow_credentials=True,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
)


# Serve built frontend if available (web/dist)
if FRONTEND_DIST.exists():
    assets_dir = FRONTEND_DIST / "assets"
    if assets_dir.exists():
        app.mount("/assets", StaticFiles(directory=str(assets_dir)), name="assets")

    @app.get("/", include_in_schema=False)
    def index() -> FileResponse:
        """Serve the React SPA entrypoint."""
        return FileResponse(str(FRONTEND_DIST / "index.html"))


@app.get("/health", response_model=HealthResponse, tags=["health"])
def health() -> HealthResponse:
    """Liveness probe. Returns ``ok`` as long as the process is running."""
    return HealthResponse(status="ok", model_loaded=app.state.model is not None)


@app.get("/ready", response_model=HealthResponse, tags=["health"])
def ready() -> HealthResponse:
    """Readiness probe. Reports whether the model is loaded.

    Returns 200 in all cases so the service can still serve the stub
    response when the model cannot be loaded, but surfaces the state
    via ``model_loaded`` for observability.
    """
    return HealthResponse(
        status="ready" if app.state.model is not None else "degraded",
        model_loaded=app.state.model is not None,
    )


@app.post("/summarize", response_model=PredictionResponse, tags=["inference"])
def summarize(payload: InputData, request: Request) -> PredictionResponse:
    """Generate a patient-friendly summary of a clinical note.

    * Enforces a naive per-IP rate limit (``RATE_LIMIT_MAX`` per
      ``RATE_LIMIT_WINDOW_SEC``).
    * Validates input size (``MAX_INPUT_CHARS``).
    * Falls back to a simple truncation if the model failed to load.
    """
    ip = request.client.host if request.client else "unknown"
    _rate_limit_check(app, ip)

    text = payload.text.strip()
    if len(text) > MAX_INPUT_CHARS:
        raise HTTPException(
            status_code=413,
            detail=f"Input too large. Max {MAX_INPUT_CHARS:,} characters.",
        )

    tokenizer = app.state.tokenizer
    model = app.state.model
    device: torch.device = app.state.device

    if tokenizer is None or model is None:
        # Stub summarization: return a trimmed version of the input.
        words = text.split()
        trimmed = " ".join(words[:50])
        return PredictionResponse(summary=trimmed if trimmed else text)

    prompt = f"summarize: {text}"
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=2048)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    max_new = payload.max_new_tokens or 256
    temp = payload.temperature or 0.0
    do_sample = temp > 0.0

    start = time.perf_counter()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new,
            num_beams=(1 if do_sample else 4),
            do_sample=do_sample,
            temperature=(temp if do_sample else None),
            length_penalty=1.0,
            no_repeat_ngram_size=3,
            early_stopping=True,
        )

    summary_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    latency_ms = int((time.perf_counter() - start) * 1000)
    logger.info(
        "summary_generated",
        extra={
            "ip": ip,
            "input_chars": len(text),
            "summary_chars": len(summary_text),
            "latency_ms": latency_ms,
            "do_sample": do_sample,
            "temperature": temp,
            "max_new_tokens": max_new,
        },
    )
    return PredictionResponse(summary=summary_text)


@app.exception_handler(HTTPException)
def http_exc_handler(_: StarletteRequest, exc: HTTPException) -> JSONResponse:
    """Return a consistent JSON error envelope for HTTPExceptions."""
    return JSONResponse(
        status_code=exc.status_code,
        content={"error": {"code": exc.status_code, "message": exc.detail}},
    )


# Optional: SPA catch-all so client-side routing works. Registered last so
# it does not shadow API routes defined above.
if FRONTEND_DIST.exists():
    app.mount("/static", StaticFiles(directory=str(FRONTEND_DIST), html=False), name="static")

    @app.get("/{full_path:path}", include_in_schema=False)
    def spa_catch_all(full_path: str) -> FileResponse:
        """Serve the SPA entrypoint for unknown non-API routes."""
        index_file = FRONTEND_DIST / "index.html"
        if index_file.exists():
            return FileResponse(str(index_file))
        raise HTTPException(status_code=404, detail="Not found")
